# Config for Overcommit, v0.63.0
#
# @see https://github.com/sds/overcommit
#
# Install:
#   bin/overcommit --install
# Run pre-commit actions now, not on git hook:
#   bin/overcommit -r
# Commit without Overcommit's checks:
#   OVERCOMMIT_DISABLE=1 git commit -m 'Commit message'
gemfile: .tools/Gemfile
plugin_directory: .tools/hooks

CommitMsg:
  CapitalizedSubject:
    enabled: false
  HardTabs:
    enabled: true
  TextWidth:
    enabled: false
  TrailingPeriod:
    enabled: false

PreCommit:
  BundleAudit:
    command: 'bin/bundle-audit'
    description: 'https://github.com/rubysec/bundler-audit'
    enabled: true
  BundleCheck:
    enabled: true
    parallelize: false
  BundleInstall:
    enabled: true
  BundleLeak:
    command: 'bin/bundle-leak'
    description: 'Make sure memory leaks are not in your gem dependencies'
    enabled: true
  Fasterer:
    command: 'bin/fasterer'
    description: 'https://github.com/DamirSvrtan/fasterer'
    enabled: true
  FileSize:
    enabled: true
    size_limit_bytes: 1048576 # 1 megabyte
  HardTabs:
    enabled: true
  RailsBestPractices:
    command: 'bin/rails_best_practices'
    description: 'https://github.com/flyerhzm/rails_best_practices'
    enabled: true
  RailsSchemaUpToDate:
    enabled: true
  RuboCop:
    command: 'bin/rubocop'
    description: 'https://rubocop.org'
    enabled: true
    on_warn: fail # Treat all warnings as failures
  SlimLint:
    command: 'bin/slimlint'
    description: 'https://github.com/sds/slim-lint'
    enabled: true
  TrailingWhitespace:
    enabled: true
    exclude:
      - '**/*.md'
      - '**/*.markdown'
      - '**/*.rb'
  # Use one of: YamlLint, YamlSyntaxChecker.
  # YamlLint:
  #   description: 'https://github.com/adrienverge/yamllint' # Requires Python 3.
  #   enabled: true
  YamlSyntaxChecker:
    enabled: true
    description: 'Check YAML syntax. Based on hook YamlSyntax.'
    required_library: 'yaml'
    include:
      - '**/*.yaml'
      - '**/*.yml'

PrePush:
  Brakeman:
    command: 'bin/brakeman'
    description: 'http://brakemanscanner.org'
    enabled: true
