requirements:
  feature:
    comment: "Feature"
    optional_data: {}
    relations:
      includes: [user_story]
    unit_of_work: false
  user_story:
    comment: "User Story"
    optional_data: {}
    relations:
      includes: [task]
    unit_of_work: false
  task:
    comment: "Task"
    optional_data:
      external_url:
        type: string
        nil: false
        default: ""
        comment: "External URL"
      min_estimated_duration:
        type: float
        nil: true
        default: ~
        min_value: 0
        max_value: 99.99
        step: 0.01
        comment: "Minimal estimated duration in hours"
      max_estimated_duration:
        type: float
        nil: true
        default: ~
        min_value: 0
        max_value: 99.99
        step: 0.01
        comment: "Maximal estimated duration in hours"
    relations:
      includes: []
    unit_of_work: true
requirement_relations:
  starts_after: "starts after"
  includes: "includes"
