# Config for Rails Best Practices, v1.23.2
#
# Common options:
#   ignored_files: Array[String]

AddModelVirtualAttributeCheck: { }

AlwaysAddDbIndexCheck: { }

# CheckSaveReturnValueCheck: { }

# CheckDestroyReturnValueCheck: { }

DefaultScopeIsEvilCheck: { }

DryBundlerInCapistranoCheck: { }

# HashSyntaxCheck: { }

IsolateSeedDataCheck: { }

KeepFindersOnTheirOwnModelCheck: { }

LawOfDemeterCheck: { }

# Options and default values:
#   max_line_length: 80
# LongLineCheck: { max_line_length: 80 }

MoveCodeIntoControllerCheck: { }

# Options and default values:
#   array_count: 3
MoveCodeIntoHelperCheck: { array_count: 3 }

# Options and default values:
#   use_count: 2
MoveCodeIntoModelCheck: { use_count: 2 }

MoveFinderToNamedScopeCheck: { }

# Options and default values:
#   use_count: 4
MoveModelLogicIntoModelCheck: { use_count: 4 }

# Options and default values:
#   nested_count: 2
NeedlessDeepNestingCheck: { nested_count: 2 }

NotRescueExceptionCheck: { }

NotUseDefaultRouteCheck: { }

NotUseTimeAgoInWordsCheck: { }

# Options and default values:
#   customize_count: 3
OveruseRouteCustomizationsCheck: { customize_count: 3 }

ProtectMassAssignmentCheck: { }

RemoveEmptyHelpersCheck: { }

# RemoveTabCheck: { }

RemoveTrailingWhitespaceCheck: { }

# Options and default values:
#   except_methods: [], Array[String]
RemoveUnusedMethodsInControllersCheck: { except_methods: [] }

RemoveUnusedMethodsInHelpersCheck: { except_methods: [] }

RemoveUnusedMethodsInModelsCheck: { except_methods: [] }

# Options and default values:
#   attribute_assignment_count: 2
ReplaceComplexCreationWithFactoryMethodCheck: { attribute_assignment_count: 2 }

ReplaceInstanceVariableWithLocalVariableCheck: { }

RestrictAutoGeneratedRoutesCheck: { }

SimplifyRenderInControllersCheck: { }

SimplifyRenderInViewsCheck: { }

# Options and default values:
#   customize_count: 2
# UseBeforeFilterCheck: { customize_count: 2 }

UseModelAssociationCheck: { }

UseMultipartAlternativeAsContentTypeOfEmailCheck: { }

# UseParenthesesInMethodDefCheck: { }

UseObserverCheck: { }

UseQueryAttributeCheck: { }

UseSayWithTimeInMigrationsCheck: { }

UseScopeAccessCheck: { }

UseTurboSprocketsRails3Check: { }
