# Config for Rubocop.

inherit_gem:
  rubocop-configs:
    - _all_cops.yml
    - _ruby.yml
    - bundler.yml
    - performance.yml
    - rails.yml
    - rake.yml
    - thread_safety.yml

AllCops:
  TargetRubyVersion: 3.3


Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - "db/migrate/*.rb"

Naming/FileName:
  Exclude:
    - .tools/Gemfile

Style/ClassAndModuleChildren:
  Exclude:
    - '.tools/**/*.rb'
